production:
  env:
    app_path:
    site:
      title: 'Gagnrath'
      sub_title: 'for Gimle'
    gvtype: FE
    sample_mode: false
    view_mode: false
    time_lock: false
    attention_minitues: 5
    data_size:
      recently: 6
      min: 4
      max: 12
    timeline:
      span_max_size: 4
    use_mail: false
    union_history:
      max_size: 20
      only_union: false
    dump_generation: 0
  memcache:
    server: localhost:11211
    namespace: hoge
    expire: 30
  auth:
    basic:
      user: hoge
      pass: piyo
    admin:
      user: amistr
      pass: mohumohu
    update_key: hogepiyo
    delete_key: fizzbuzz
development:
  env:
    app_path:
    site:
      title: 'Gagnrath'
      sub_title: 'for Nounai'
    gvtype: FE
    sample_mode: false
    view_mode: false
    time_lock: false
    attention_minitues: 5
    data_size:
      recently: 6
      min: 4
      max: 12
    timeline:
      span_max_size: 4
    use_mail: false
    union_history:
      max_size: 20
      only_union: false
    dump_generation: 0
  memcache:
    server: localhost:11211
    namespace: devel
    expire: 3
  auth:
    basic:
      user: hoge
      pass: piyo
    admin:
      user: amistr
      pass: mohumohu
    update_key: hogepiyo
    delete_key: fizzbuzz
test:
  env:
    app_path:
    site:
      title: 'Gagnrath'
      sub_title: 'for SakrayJ'
    gvtype: FE
    sample_mode: false
    view_mode: false
    time_lock: false
    attention_minitues: 5
    data_size:
      recently: 6
      min: 4
      max: 12
    timeline:
      span_max_size: 4
    use_mail: false
    union_history:
      max_size: 20
      only_union: false
    dump_generation: 0
  memcache:
    server: localhost:11211
    namespace: test
    expire: 1
  auth:
    basic:
      user: hoge
      pass: piyo
    admin:
      user: amistr
      pass: mohumohu
    update_key: hogepiyo
    delete_key: fizzbuzz
